feature/course-1
b00tc4mp/ubiqum-bootcamp pull request #30
Opened 2021-02-04 16:10 UTC by pujabhattacharya1

Merging website code base of puja bhattacharya

2021-02-10 16:28 UTC, manuelbarzi requested changes

2021-02-10 16:28 UTC, manuelbarzi commented on staff/puja-bhattacharya/course-1/ver-0/index.html
> +            <div>
should links be contained in a nav element, instead of a div, for semantics.

2021-02-10 16:28 UTC, manuelbarzi commented on staff/puja-bhattacharya/course-1/ver-0/index.html
> +        <table>
should table not be used for layout, but for specifically showing table data content. may you consider using a a grid layout instead, applied to a section.

2021-02-10 16:28 UTC, manuelbarzi commented on staff/puja-bhattacharya/course-1/ver-0/index.html
> +                    <article class="all-browsers">
should article be used for independent and self-contained content, but not for related elements like here the events in this events list (for instance).

2021-02-10 16:28 UTC, manuelbarzi commented on staff/puja-bhattacharya/course-1/ver-0/contact.html
> +                <table>
should table not be used for layout, but for table showable data (ex: statistic results, excel-like stuff, etc)

2021-02-10 16:28 UTC, manuelbarzi commented on staff/puja-bhattacharya/course-1/ver-0/contact.html
> +        <table>
same here, should tables not be used for layout, but for table-friendly data only

2021-02-10 16:28 UTC, manuelbarzi commented on staff/puja-bhattacharya/course-1/ver-0/about.html
> +                <table>
should table not be used for layout, but for table-friendly data

2021-02-11 10:46 UTC, RoseKoning reviewed
I hope this helps!

2021-02-11 10:46 UTC, RoseKoning commented on staff/puja-bhattacharya/course-1/ver-0/about.html
> +            <div>
To make it more semantically correct you could for example use a <ul> element with the <a> insiden and <li> element

2021-02-11 10:46 UTC, RoseKoning commented on staff/puja-bhattacharya/course-1/ver-0/contact.html
> +                            <br><br>
<br> is used more for adding white spaces into your text. If you want to add white spaces in your layout, you should try using padding/margin

2021-02-11 10:46 UTC, RoseKoning commented on staff/puja-bhattacharya/course-1/ver-0/css/style.css
> +    left: 0;
if  you sent margin to 0, you don´t need left and right. Also if you have width 100% you probably don´t need adjusting at all

2021-02-11 10:46 UTC, RoseKoning commented on staff/puja-bhattacharya/course-1/ver-1_responsive/index.html
> +            <a class="active">Home</a> |
<ul> with <li> might make it better

2021-02-11 11:54 UTC, manuelbarzi commented on staff/puja-bhattacharya/course-1/ver-1_responsive/index.html
> +        <div class = "navigation-menu">
may you wrap navigation elements inside `nav`instead of `div`

2021-02-11 12:05 UTC, manuelbarzi requested changes

2021-02-11 12:05 UTC, manuelbarzi commented on staff/puja-bhattacharya/course-1/ver-1_responsive/index.html
> +        <div class = "navigation-menu">
may you wrap navigation elements inside `nav`instead of `div`

2021-02-12 11:38 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-1_responsive/index.html
> +        <div class = "navigation-menu">
the navigation menu is wrapped inside nav in updated version of the code. However, the company name could not be fit now as it is adjusted in grid and changing only that part will incorporate a lot of changes to the whole website layout.

2021-02-12 11:41 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/index.html
> +            <div>
the information about semantics was not there while coding ver0, however the changes are there in updated version

2021-02-12 11:41 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/index.html
> +        <table>
the information about semantics was not there while coding ver0, however the changes are there in updated version

2021-02-12 11:41 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/index.html
> +                    <article class="all-browsers">
the information about semantics was not there while coding ver0, however the changes are there in updated version

2021-02-12 11:42 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/contact.html
> +                <table>
the information about semantics and clean coding was not there while coding ver0, however the changes are there in updated version

2021-02-12 11:42 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/contact.html
> +        <table>
the information about semantics and clean coding was not there while coding ver0, however the changes are there in updated version

2021-02-12 11:42 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/about.html
> +                <table>
the information about semantics and clean coding was not there while coding ver0, however the changes are there in updated version

2021-02-12 11:43 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/about.html
> +            <div>
the information about semantics and clean coding was not there while coding ver0, however the changes are there in updated version

2021-02-12 11:46 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/contact.html
> +                            <br><br>
the information about semantics and clean coding was not there while coding ver0, however the changes are there in updated version

2021-02-12 11:49 UTC, pujabhattacharya1 commented on staff/puja-bhattacharya/course-1/ver-0/css/style.css
> +    left: 0;
The changes are already incorporated there in updated version.

2021-03-01 10:41 UTC, merged