Feature/task 1
b00tc4mp/ubiqum-bootcamp pull request #31
Opened 2021-02-04 20:06 UTC by death4santamarta

2021-02-10 09:21 UTC, manuelbarzi commented on staff/enric-santamarta-bendicho/task1/home.html
> +    <a href="home.html">  Home|</a>
should you use a list item (li) for each one of the anchors (a). if you require the list items to show horizontally and with the vertical line separator, you can style it playing with the borders (for instance).

2021-02-10 09:21 UTC, manuelbarzi commented on staff/enric-santamarta-bendicho/task1/img/Website_Sketch.webloc
> +<?xml version="1.0" encoding="UTF-8"?>
what is the purpose of this file here?

2021-02-10 09:21 UTC, manuelbarzi commented on staff/enric-santamarta-bendicho/task1/home.html
> +<h1 class="head3">Upcoming Events</h1>
should you consider avoiding more than one h1 for SEO purposes (https://www.reliablesoft.net/difference-between-page-title-h1-tag/).

2021-02-10 09:21 UTC, manuelbarzi commented on staff/enric-santamarta-bendicho/task1/home.html
> +<p class ="paragraph3">August 4</p>
may a list be more appropiate for listing the events here (ul / li) and playing with styles to make it show as your projection

2021-02-10 16:03 UTC, manuelbarzi requested changes

2021-02-10 16:03 UTC, manuelbarzi commented on staff/enric-santamarta-bendicho/task1/about.html
> +  <div>
is this div necessary or present here for any reason?

2021-02-10 16:05 UTC, manuelbarzi requested changes

2021-02-10 16:05 UTC, manuelbarzi commented on staff/enric-santamarta-bendicho/task1/style.css
> +*{
the wildcard * is used to select all elements and apply styles to all of them, but here is empty. should it be removed then?

2021-02-11 14:54 UTC, manuelbarzi commented on staff/enric-santamarta-bendicho/task1/contact.html
> +      <li>
should each link be contained in a separate list item, instead of all them contained into one. list items (li) are designed to be used in lists (ul / ol) to describe diferent items. it is perfectly valid in a nav, that's fine, but the anchors should be contained in own list items.

2021-02-11 15:31 UTC, death4santamarta commented on staff/enric-santamarta-bendicho/task1/about.html
> +  <div>
removed

2021-02-11 15:32 UTC, death4santamarta commented on staff/enric-santamarta-bendicho/task1/home.html
> +    <a href="home.html">  Home|</a>
done

2021-02-11 15:33 UTC, death4santamarta commented on staff/enric-santamarta-bendicho/task1/home.html
> +<p class ="paragraph3">August 4</p>
done

2021-02-11 15:33 UTC, death4santamarta commented on staff/enric-santamarta-bendicho/task1/about.html
> +  <div>
removed

2021-02-11 15:33 UTC, death4santamarta commented on staff/enric-santamarta-bendicho/task1/style.css
> +*{
removed

2021-02-11 15:33 UTC, death4santamarta commented on staff/enric-santamarta-bendicho/task1/contact.html
> +      <li>
done

2021-02-11 15:40 UTC, death4santamarta commented on staff/enric-santamarta-bendicho/task1/home.html
> +<h1 class="head3">Upcoming Events</h1>
done

2021-02-11 15:45 UTC, death4santamarta commented on staff/enric-santamarta-bendicho/task1/img/Website_Sketch.webloc
> +<?xml version="1.0" encoding="UTF-8"?>
I can remove it to, should I delete the Branch and pushed it again?

2021-03-01 10:45 UTC, merged