Feature/course 1
b00tc4mp/ubiqum-bootcamp pull request #34
Opened 2021-02-07 22:56 UTC by lucalm91

2021-02-11 08:23 UTC, manuelbarzi requested changes

2021-02-11 08:23 UTC, manuelbarzi commented on staff/luca-lamorte/feature/course-1/NYSL/home.html
> +        <div class="hero">
is this wrapping div (hero) necessary?

2021-02-11 08:23 UTC, manuelbarzi commented on staff/luca-lamorte/feature/course-1/NYSL/home.html
> +        <div class="events">
may this be a section?

2021-02-11 08:23 UTC, manuelbarzi commented on staff/luca-lamorte/feature/course-1/NYSL/home.html
> +            <div class="event-container">
may you list events in a ul element?

2021-02-11 10:39 UTC, RoseKoning commented on staff/luca-lamorte/feature/course-1/NYSL/about-us.html
> +        <div class="hero">
You might not need a div for a <h1> element in a header

2021-02-11 10:39 UTC, RoseKoning commented on staff/luca-lamorte/feature/course-1/NYSL/about-us.html
> +        <div class="about-us-container">
this could also be a < section> element

2021-03-24 12:50 UTC, manuelbarzi commented
There has been a change in the `upstream` repo, please, re-do this PR against your new branch `develop-<your-program-year-month`>. Thank you!

2021-03-24 12:50 UTC, closed without merging