Feature/course 1
b00tc4mp/ubiqum-bootcamp pull request #35
Opened 2021-02-09 16:42 UTC by davide-st

2021-02-10 16:34 UTC, manuelbarzi commented on staff/davide-stefani/course-1/sketch/home.html
> +    <img class="logo" src="images/nysl_logo.png">
isn't this logo image part of the header?

2021-02-10 16:40 UTC, manuelbarzi commented on staff/davide-stefani/course-1/sketch/home.html
> +    <section class="subheader">
should a section be used to just contain a title? in case not, may you set the styles directly in the heading element or use a div

2021-02-10 16:42 UTC, manuelbarzi commented on staff/davide-stefani/course-1/sketch/home.html
> +            <a href="home.html">
should list items (li) contains anchors, but not the inverse?

2021-02-10 16:44 UTC, manuelbarzi requested changes

2021-02-10 16:44 UTC, manuelbarzi commented on staff/davide-stefani/course-1/sketch/home.html
> +        <article>
should articles be used to independent and self-contained content, but events are related to the agenda of events, do it apply to have them in articles?

2021-02-11 10:00 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/home.html
> +        <article>
Article element specifies independent, self-contained content, as in here we have an thematic grouping of content and I decided to regroup and change the element to section.

2021-02-11 10:00 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/home.html
> +            <a href="home.html">
Agreed with you, I should have put the anchors inside the list items.

2021-02-11 10:01 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/home.html
> +    <section class="subheader">
I found in internet that section typically have a heading but not always. For this reason I did change it to div as you suggested.

2021-02-11 10:01 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/home.html
> +    <img class="logo" src="images/nysl_logo.png">
I did create a different grid just for the logo image but it would make more sense to be a part of the header. I will try to adjust it and add it to the header

2021-02-11 10:33 UTC, RoseKoning reviewed
Hi davide, I hope this helps.

2021-02-11 10:33 UTC, RoseKoning commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p><label>
Hi  davide, to be semantically correct, you shouldn´t put the <input> inside of the <label>. If you did it to be able to style it better, you can use a div or other suitable element to group them together and give the class to that group element.

2021-02-11 10:33 UTC, RoseKoning commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p>What position(s) do you normally play? (check all that apply)</p>
This could for example be a <ul> with <li> elements inside so that you can improve the semantics.(this goes for all the form questions where you have lots of answers)

2021-02-11 10:33 UTC, RoseKoning commented on staff/davide-stefani/course-1/sketch/style.css
> +    display: grid;
is there are reason you are making another grid inside of the header?

2021-02-11 12:17 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/style.css
> +    display: grid;
no reason. I. did copy and paste and did not realize about it! thanks

2021-02-11 13:10 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p>What position(s) do you normally play? (check all that apply)</p>
Not sure what you mean. Can you explain better how can I improve the semantics? thanks

2021-02-11 13:12 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p><label>
what you mean with the inside of the . ? I didn't quite understand how to make it semantically correct. Thanks

2021-02-11 16:09 UTC, RoseKoning commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p><label>
Ok. RIght now you have <label><input></label> so your input is inside of your label. so if you want to do it correctly you do <input><label></label>.

If you want to put them in a section so you can style them as a section, you can do:
<div><input><label></label></div>

2021-02-11 16:10 UTC, RoseKoning commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p>What position(s) do you normally play? (check all that apply)</p>
sorry the items disappeared. < ul> with < li> elements inside. Because then seo can see it´s a list

2021-02-11 16:13 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p><label>
Rose I am not able to see the codes you writing. not sure why

2021-02-11 16:14 UTC, davide-st commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p>What position(s) do you normally play? (check all that apply)</p>
Ok! cool! now I understand. thanks

2021-02-11 16:22 UTC, RoseKoning commented on staff/davide-stefani/course-1/sketch/registration.html
> +            <p><label>
< input>< label>< /label>option one. 

< div>< input>< label>< /label> < /div> option two if you want to style them together

2021-03-01 10:43 UTC, merged