Feature/project 2
b00tc4mp/ubiqum-bootcamp pull request #43
Opened 2021-03-24 12:55 UTC by RoseKoning

2021-04-09 14:13 UTC, manuelbarzi commented on staff/rose-koning/project-2/sprint-4/task-6/congress/home.html
> +                <button onclick="myFunction()" id="myBtn">Read more</button>
correct the behavior error when clicking on this button => 

```js
home.html:87 Uncaught ReferenceError: myFunction is not defined
    at HTMLButtonElement.onclick (home.html:87)
```

2021-04-09 14:17 UTC, manuelbarzi commented on staff/rose-koning/project-2/sprint-3/task-5/legislators.html
> +<!DOCTYPE html>
correct the links to Home, Congress 113, Attendance. right now they do not work => `Cannot GET /staff/rose-koning/project-2/sprint-3/task-5/ ...`

2021-04-19 07:31 UTC, RoseKoning commented on staff/rose-koning/project-2/sprint-4/task-6/congress/home.html
> +                <button onclick="myFunction()" id="myBtn">Read more</button>
This function is working on my computer. The function myFunction is located in the main

2021-04-19 07:53 UTC, RoseKoning commented on staff/rose-koning/project-2/sprint-3/task-5/legislators.html
> +<!DOCTYPE html>
fixed

2021-04-21 21:58 UTC, manuelbarzi commented on staff/rose-koning/project-2/sprint-4/task-6/congress/house-data.html
> +<!DOCTYPE html>
house data fails on page load
```js
congress-data.js:1 Uncaught ReferenceError: url is not defined
    at congress-data.js:1
(anonymous) @ congress-data.js:1
```

2021-04-21 22:01 UTC, manuelbarzi commented on staff/rose-koning/project-2/sprint-4/task-6/congress/home.html
> +<!DOCTYPE html>
congress and attendance links point to the same pages, but they should show different pages with different information. attendance pages are missing here in this task-6. please, add them and correct the links.

2021-04-21 22:02 UTC, manuelbarzi requested changes
review the comments and update the project to make it work property.

2021-05-31 09:24 UTC, merged